// DO NOT ADD IMPORTS TO '*.d.ts' files!
// https://stackoverflow.com/a/51114250

declare namespace meshoptimizer {
  type U32Ptr = WasmPtr;
  type F32Ptr = WasmPtr;
  type U8Ptr = WasmPtr;
  type SizeT = number;

  /**
   * Generates a vertex remap table from the vertex buffer and an optional index buffer and returns number of unique vertices.
   *
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/meshoptimizer.h#L59
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/indexgenerator.cpp#L201
   */
  export function meshopt_generateVertexRemap(
    destination: U32Ptr, // unsigned int* destination,
    indices: U32Ptr, // const unsigned int* indices,
    index_count: SizeT, // size_t index_count,
    vertices: F32Ptr, // const void* vertices,
    vertex_count: SizeT, // size_t vertex_count,
    vertex_size: SizeT // size_t vertex_size
  ): number;

  /**
   * Generate index buffer from the source index buffer and remap table generated by meshopt_generateVertexRemap.
   *
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/meshoptimizer.h#L88
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/indexgenerator.cpp#L341
   */
  export function meshopt_remapIndexBuffer(
    destination: U32Ptr, // unsigned int* destination,
    indices: U32Ptr, // const unsigned int* indices,
    index_count: SizeT, // size_t index_count,
    remap: U32Ptr // const unsigned int* remap
  ): void;

  /**
   * Generates vertex buffer from the source vertex buffer and remap table generated by meshopt_generateVertexRemap
   *
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/meshoptimizer.h#L80
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/indexgenerator.cpp#L305
   */
  export function meshopt_remapVertexBuffer(
    destination: F32Ptr, // const void* destination,
    vertices: F32Ptr, // const void* vertices,
    vertex_count: SizeT, // size_t vertex_count,
    vertex_size: SizeT, // size_t vertex_size,
    remap: U32Ptr // const unsigned int* remap
  ): void;

  /**
   * Reduces the number of triangles in the mesh, attempting to preserve mesh appearance as much as possible.
   *
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/meshoptimizer.h#L350
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/simplifier.cpp#L1640
   */
  export function meshopt_simplify(
    destination: U32Ptr, // unsigned int* destination,
    indices: U32Ptr, // const unsigned int* indices,
    index_count: SizeT, // size_t index_count,
    vertices: F32Ptr, // const float* vertex_positions_data,
    vertex_count: SizeT, // size_t vertex_count,
    vertex_positions_stride: SizeT, // size_t vertex_positions_stride,
    target_index_count: SizeT, // size_t target_index_count,
    target_error: number, // float target_error,
    options: number, // unsigned int options,
    out_result_error: F32Ptr // float* out_result_error
  ): SizeT;

  /**
   * Returns the error scaling factor used by the simplifier to convert between absolute and relative extents
   *
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/meshoptimizer.h#L399
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/simplifier.cpp#L1903
   */
  export function meshopt_simplifyScale(
    vertices: F32Ptr, // const float* vertex_positions,
    vertex_count: SizeT, // size_t vertex_count,
    vertex_positions_stride: SizeT // size_t vertex_positions_stride
  ): number;

  /**
   * Splits the mesh into a set of meshlets where each meshlet has a micro index buffer indexing into meshlet vertices that refer to the original vertex buffer
   *
   * https://github.com/zeux/meshoptimizer/blob/3c3e56d312cbe7d5929c78401de2124c7be3bc07/src/meshoptimizer.h#L493
   * https://github.com/zeux/meshoptimizer/blob/5bc5ed0b6f64d20f29342da9acaa27648fb45500/src/clusterizer.cpp#L535
   */
  export function meshopt_buildMeshlets(
    meshlets: U32Ptr, // meshopt_Meshlet* meshlets,
    meshlet_vertices: U32Ptr, // unsigned int* meshlet_vertices,
    meshlet_triangles: U8Ptr, // unsigned char* meshlet_triangles,
    indices: U32Ptr, // const unsigned int* indices,
    index_count: SizeT, // size_t index_count,
    vertices: F32Ptr, // const float* vertex_positions,
    vertex_count: SizeT, // size_t vertex_count,
    vertex_positions_stride: SizeT, // size_t vertex_positions_stride
    max_vertices: SizeT, // size_t max_vertices,
    max_triangles: SizeT, // size_t max_triangles,
    cone_weight: number // float cone_weight
  ): SizeT;

  /** https://github.com/zeux/meshoptimizer/blob/5bc5ed0b6f64d20f29342da9acaa27648fb45500/src/clusterizer.cpp#L513 */
  export function meshopt_buildMeshletsBound(
    index_count: SizeT, // size_t index_count,
    max_vertices: SizeT, // size_t max_vertices,
    max_triangles: SizeT // size_t max_triangles,
  ): SizeT;

  /** https://github.com/zeux/meshoptimizer/blob/5bc5ed0b6f64d20f29342da9acaa27648fb45500/src/clusterizer.cpp#L865 */
  export function meshopt_computeMeshletBounds(
    returnValue_meshopt_Bounds: F32Ptr, // return value is put on heap. Bytes: sizeof(meshopt_Bounds)
    meshlet_vertices: U32Ptr, // unsigned int* meshlet_vertices,
    meshlet_triangles: U8Ptr, // unsigned char* meshlet_triangles,
    triangle_count: SizeT, // size_t triangle_count,
    vertex_positions: F32Ptr, // const float* vertex_positions,
    vertex_count: SizeT, // size_t vertex_count,
    vertex_positions_stride: SizeT // size_t vertex_positions_stride
  ): SizeT;
}
